apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dealers-bid
    app.kubernetes.io/instance: dealers-bid-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: dealers-bid
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealers-bid
  template:
    metadata:
      labels:
        app: dealers-bid
    spec:
      containers:
        - image: 920871934450.dkr.ecr.us-east-1.amazonaws.com/dealers-bid:latest
          imagePullPolicy: Always
          name: dealers-bid
          ports:
            - containerPort: 80
