apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dealers-bid
    app.kubernetes.io/instance: dealers-bid-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: dealers-bid
  namespace: dev
spec:
  selector:
    app: dealers-bid
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
